version = 1

exclude_patterns = [
    ".github/**",
    "docs/**",
    "examples/static/**",
    "fixtures/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  environment = ["nodejs"]
  dialect = "typescript"